version: 1
formatters:
  simple:
    format: '%(asctime)s - %(filename)s[line:%(lineno)d] - %(levelname)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    filename: logs/fairyseason.log
    when: d
    interval: 1
    backupCount: 30
    formatter: simple
#  warn_file_handler:
#      class: logging.handlers.RotatingFileHandler
#      level: WARN
#      formatter: standard
#      filename: /tmp/warn.log
#      maxBytes: 10485760 # 10MB
#      backupCount: 20
#      encoding: utf8
loggers:
  simpleExample:
    level: INFO
    handlers: [console_handler, file_handler]
    propagate: no
root:
  level: INFO
  handlers: [console_handler]
